---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    name: kafka
    # Restricted pod security – Strimzi handles its own security context
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
